### PR TITLE
Add parameter to allow skipping node creation

### PR DESCRIPTION
**Pull request by tkalmar**
Superseeds #14  Redone on current code.

### CODE REVIEW

**Comment by tkalmar** [comment]
@oleg-nenashev ping

**Comment by oleg-nenashev** [comment]
Hi. I stepped down as a plugin maintainer in 2018. @escoem is the new maintainer

**Comment by stepancar** [comment]
@oleg-nenashev can we release it?

**Comment by aso1datov** [comment]
@escoem can you release this feature please?

**Comment by oleg-nenashev** [comment]
Sorry, I have not been maintaining this plugin for long time. I guess @escoem would not mind if I release the new version though

**Comment by anderius** [comment]
@oleg-nenashev, @escoem Did that release ever happen? :-)

**Pull request merged**
