### PR TITLE
using checkout instead of git because because git doesn't manage tags

### PR DESCRIPTION
**Pull request by escoem**
@reviewbybees esp @oleg-nenashev @amuniz

### CODE REVIEW

**Comment by amuniz** [comment]
LGTM :bee:

**Comment by oleg-nenashev** [comment]
:bee: for the change after the discussion. BTW, I feel it's likely a bug in the Pipeline stuff, so it would be great to have a test case reproducing the issue

**Comment by escoem** [comment]
thanks @oleg-nenashev , I will do the test before :-)

**Comment by jglick** [comment]
What bug? The `branch` parameter is explicitly documented to take a branch name, not a tag.

The `git` step is only intended as a shortcut for the most commonly used simple options, which is irrelevant in library code. If you want exotic options, use `checkout` with `GitSCM` as you are here.

**Comment by escoem** [comment]
Thanks @jglick, in that case as we need those exotic options, please @oleg-nenashev can you merge it?

**Pull request merged**
