### PR TITLE
[WiP] Step that loads remote library in a similar way to cps global lib.

### PR DESCRIPTION
**Pull request by rsandell**
Todo
- [x] Add the test git as a resource
- [ ] Checkout bare repo in a central place and just do reference checkout to the branch in the build dir to save space and time
- [ ] Solve calling workflow steps and vars from classes in src
- [ ] Documentation and config page

@reviewbybees

### CODE REVIEW

**Comment by rsandell** [comment]
Not being able to call workflow steps and vars from classes in src is probably an issue in global lib as well, but I would like to solve it because I need it ;)

**Comment by oleg-nenashev** [comment]
@rsandell :+1: . Kudos for hacking this feature

> Not being able to call workflow steps and vars from classes in src is probably an issue in global lib as well, but I would like to solve it because I need it ;)

I suppose you should take a look on https://github.com/jenkinsci/workflow-plugin/tree/master/cps-global-lib#writing-shared-code

**Comment by rsandell** [comment]
The test failure is expected, It's in the middle of a reimplementation.

**Comment by jglick** [comment]
I believe this is superseded by https://github.com/jenkinsci/workflow-cps-global-lib-plugin/pull/10.

**Comment by oleg-nenashev** [comment]
@jglick IMHO yes

**Comment by rsandell** [comment]
Indeed, no longer needed with shared libraries in "core pipeline"

**Pull request closed without merging**
